<template>
  <div>
    <div class="textOfSlider">
      The #2 It’s time to do something good for your wallet and the Earth Some
      Thing Like That
    </div>
    <div class="alisarView"><AlisarView /></div>
    <div class="imnew">
      <img src="../assets/e.jpg" class="imimim" />
      <div class="imimnew">bfdbbbbbbbbbbbbbbbbbbbb</div>
      <div class="textOfNew">
        <div class="op1">
          $ Solar panels, also known as photovoltaic modules, are devices that
          convert sunlight into electricity through the photovoltaic effect.
        </div>
        <div class="op1">
          $$ The batteries store excess electricity generated by solar panels
          during sunny days and release it during times when sunlight is not
          available
        </div>
        <div class="op1">
          $$$ Inverters responsible for transforming the DC electricity produced
          by solar panels into the form of electricity that is compatible with
          the electrical grid and household wiring.
        </div>
      </div>
    </div>
    <div class="slider">
      <div class="slides" :style="slidesStyle">
        <div class="slide" v-for="(slide, index) in slides" :key="index">
          <img :src="slide.image" :alt="slide.alt" />
        </div>
      </div>
      <button @click="prevSlide">Previous</button>
      <button @click="nextSlide">Next</button>
    </div>
  </div>
</template>

<script>
import AlisarView from "@/components/AlisarView.vue";
import image1 from "@/assets/fromWork/22/1_-V7G_cvurP4b9xinUv0J2w.jpg";
import image2 from "@/assets/fromWork/22/10kW-solar-perth-1024x576.jpg";
import image3 from "@/assets/fromWork/22/ADT-Solar-modern-smart-home-with-solar-panels-scaled.jpeg";
//import image4 from "@/assets/fromWork/22/resized.jpg";
import image5 from "@/assets/solar-panels.jpg";
export default {
  name: "sliderView",
  data() {
    return {
      currentSlide: 0,
      slides: [
        {
          image: image1,
          alt: "Slide 1",
        },
        {
          image: image2,
          alt: "Slide 2",
        },
        {
          image: image3,
          alt: "Slide 3",
        },
        {
          image: image5,
          alt: "Slide 3",
        },
      ],
      intervalId: null,
    };
  },
  components: {
    AlisarView,
  },
  computed: {
    slidesStyle() {
      return {
        transform: `translateX(-${this.currentSlide * 100}%)`,
      };
    },
  },
  methods: {
    nextSlide() {
      if (this.currentSlide < this.slides.length - 1) {
        this.currentSlide++;
      } else {
        this.currentSlide = 0;
      }
    },
    prevSlide() {
      if (this.currentSlide > 0) {
        this.currentSlide--;
      } else {
        this.currentSlide = this.slides.length - 1;
      }
    },
  },
  mounted() {
    this.intervalId = setInterval(() => {
      this.nextSlide();
    }, 7000);
  },
  beforeUnmount() {
    clearInterval(this.intervalId);
  },
};
</script>

<style scoped>
@media screen and (min-width: 781px) and (max-width: 7800px) {
  .textOfNew {
    position: relative;
    display: block;
    margin-top: 160px;
    background-color: rgba(255, 255, 255, 0.3);
    left: 44%;
    height: 400px;
    width: 50%;
    border-radius: 30px;
    color: #000000;
    justify-content: center;
  }
  .imnew {
    background-color: #3e849d;
    border-radius: 0px;
    position: absolute;
    display: block;
    top: 5700px;
    height: 800px;
    width: 100%;
    background-repeat: no-repeat;
    background-position: 100% 50%;
    background-size: cover;
  }
  .imimim {
    border-radius: 0px;
    position: absolute;
    display: block;
    top: 10%;
    height: 600px;
    width: 40%;
    border-radius: 30px;
    left: 70px;
  }
  .imimnew {
    background-image: url(../assets/fromWork/light.jpg);
    height: 500px;
    width: 500px;
    background-repeat: no-repeat;
    background-position: 100% 50%;
    background-size: cover;
    border-radius: 30px;
    display: block;
    position: absolute;
    top: 5800px;
    left: 100px;
  }
  .op1 {
    margin: 40px;
    font-size: 20px;
    margin-top: 50px;
    display: block;
    top: 20px;
    position: relative;
  }
  .alisarView {
    position: absolute;
    display: block;
    height: 1000px;
    width: 100%;
    background-image: linear-gradient(white, #3e849d);
    top: 4700px;
  }
  .textOfSlider {
    font-size: 5rem;
    margin-bottom: 0.5rem;
    color: #181818;
    text-align: center;
    font-family: Roobert, sans-serif;
    max-width: 1200px;
    margin: 60px;
    text-align: center;
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    position: absolute;
    top: 4200px;
  }
  .slider {
    position: absolute;
    overflow: hidden;
    top: 7900px;
    height: 1100px;
  }
  .slides {
    display: flex;
    transition: transform 0.6s ease;
  }
  .slide {
    width: 100%;
    flex-shrink: 0;
  }
  img {
    width: 100%;
    height: auto;
  }
  button {
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
    background-color: transparent;
    border: none;
    font-size: 2rem;
    color: #fff;
    cursor: pointer;
    padding: 0 0.5rem;
    background-color: rgba(0, 0, 0, 0.3);
    border-radius: 0.25rem;
  }
  button:hover {
    background-color: rgba(0, 0, 0, 0.5);
  }
  button:first-of-type {
    left: 0;
  }
  button:last-of-type {
    right: 0;
  }
}
@media screen and (min-width: 540px) and (max-width: 680px) {
  .alisarView {
    position: relative;
    display: block;
    height: 1200px;
    width: 100%;
    background-image: linear-gradient(white, #82b1c0);
    top: 10px;
  }
  .textOfSlider {
    position: relative;
    font-family: Roobert, sans-serif;
    max-width: 800px;
    margin: 10px 10px;
    text-align: center;
    display: inline-block;
    flex-wrap: wrap;
    justify-content: center;
    padding: 20px;
    background-color: #fff;
    font-size: 4rem;
  }
  .slider {
    position: relative;
    overflow: hidden;
    top: 10px;
    height: auto;
    margin-bottom: 0%;
  }
  .slides {
    display: flex;
    transition: transform 0.6s ease;
  }
  .slide {
    width: 100%;
    flex-shrink: 0;
  }
  img {
    width: 100%;
    height: 100%;
  }
  button {
    position: absolute;
    top: 20%;
    transform: translateY(-50%);
    background-color: transparent;
    border: none;
    font-size: 2rem;
    color: #fff;
    cursor: pointer;
    padding: 0 0.5rem;
    background-color: rgba(0, 0, 0, 0.3);
    border-radius: 0.25rem;
  }
  button:hover {
    background-color: rgba(0, 0, 0, 0.5);
  }
  button:first-of-type {
    left: 0;
  }
  button:last-of-type {
    right: 0;
  }
}
</style>
